spring:
  application:
    name: boot-monitoring

  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: true
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: "health, info, metrics, prometheus"
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    "[org.hibernate.SQL]": debug
    "[org.hibernate.type.descriptor.sql]": trace
