spring:
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE
    username: sa

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      javax.persistence.sharedCache.mode: ENABLE_SELECTIVE
      hibernate:
        show_sql: false
        format_sql: true
#        generate_statistics: true
        cache:
          redisson:
            config: redisson.yml
            fallback: true
          default_cache_concurrency_strategy: read-write
          use_second_level_cache: true
          region.factory_class: org.redisson.hibernate.RedissonRegionFactory

    open-in-view: true

logging:
  level:
    "[org.hibernate.SQL]": debug
    "[org.hibernate.type.descriptor.sql.BasicBinder]": trace