cloud:
  aws:
    credentials:
      access-key: test
      secret-key: test
    region:
      static: us-east-1 # 로컬에서 실행할 경우 localstack region
    stack:
      auto: false  # 로컬에서 실행할 경우 자동 스택감지 비활성화
    sqs:
      endpoint: http://localhost:4566
