spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/dbunit
    username: root
    password: 111111

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false