### actuator env
GET http://localhost:8888/actuator/env

### actuator env update
POST http://localhost:8888/actuator/env
Content-Type: application/json

{
  "name":"spring.application.name",
  "value": "config-update-name"
}

### actuator 'spring.application.name' env 조회
### actuator env
GET http://localhost:8888/actuator/env/spring.application.name

### 프로퍼티 조회
### /{application}/{profile}[/{label}]
GET http://localhost:8888/api/dev
