management:
  endpoints:
    web:
      exposure:
        include:
          - "gateway"
spring:
  application:
    name: gateway-server
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0

  cloud:
    gateway:
      default-filters:
#        - PrefixPath=/v1
        - AddRequestHeader=X-Request-Header, req
        - AddResponseHeader=X-Response-Header, res
      routes:
        - id: user_route
          uri: http://localhost:9999
          metadata:
            sampleKey: sampleValue
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user/?(?<segment>.*), /$\{segment}

        - id: board_route
          uri: http://localhost:9999
          predicates:
            - Path=/board/**
          filters:
            - RewritePath=/board/?(?<segment>.*), /$\{segment}

        - id: auth_route
          uri: http://localhost:9999
          predicates:
            - Path=/auth/**
          filters:
            - JwtAuthentication=ROLE_ADMIN

        - id: default_route
          uri: http://localhost:9999
          predicates:
            - Path=/**

jwt:
  secret: secret
  expiration-second: 28800
