management:
  endpoints:
    web:
      exposure:
        include:
          - "gateway"
spring:
  application:
    name: gateway-server

  cloud:
    gateway:
      default-filters:
#        - PrefixPath=/v1
        - AddRequestHeader=X-Request-Header, req
        - AddResponseHeader=X-Response-Header, res
      routes:
        - id: user_route
          uri: http://localhost:9999
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user/?(?<segment>.*), /$\{segment}

        - id: board_route
          uri: http://localhost:9999
          predicates:
            - Path=/board/**
          filters:
            - RewritePath=/board/?(?<segment>.*), /$\{segment}

        - id: default_route
          uri: http://localhost:9999
          predicates:
            - Path=/**
