spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/lock
    username: root
    password: 111111

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

logging:
  level:
    org.hibernate:
      SQL: debug