spring:
  profiles:
    active: local
  application:
    name: web
  config:
    import: 'aws-parameterstore:'

aws:
  paramstore:
    endpoint: http://localhost:4566

#custom: # 바로 주입 가능하므로 주석처리함
#  username: ${custom.username}  # parameter store 의 값 주입
#  password: ${custom.password}  # parameter store 의 값 주입
