server:
  port: 8080

feign:
  custom:
    google-url: https://google.com
    facebook-url: https://test.facebook.com

  circuitbreaker:
    enabled: true

logging:
  level:
    "[com.ask.openfeign]": debug
