server:
  port: 8080

resilience4j:
  timelimiter:
    configs:
      default:
        timeoutDuration: 5s

feign:
  custom:
    google-url: https://google.com
    facebook-url: https://test.facebook.com
    sample-url: http://localhost:${server.port}

  circuitbreaker:
    enabled: true

logging:
  level:
    "[com.ask.openfeign]": debug
