springdoc:
  version: '@project.version@'
  packages-to-scan: com.ask.springdoc
  api-docs:
    path: /api-docs
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha
    path: /swagger
    disable-swagger-default-url: true
    use-root-path: true
