cloud:
  aws:
    credentials:
      access-key: test
      secret-key: test
    region:
      static: us-east-1
    stack:
      auto: false
    sns:
      endpoint: http://localhost:4566
      verification: false # LocalStack 사용시엔 signature 를 확인하지 않도록 지정
