spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/remotemeeting
    username: root
    password: 111111

  cache:
    redis:
      key-prefix: '1.1.0:cache:'

#  main:
#    allow-circular-references: true
