spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/remotemeeting
    username: root
    password: 111111

  cache:
    type: REDIS # 구현체 하나일 경우 생략 가능
    redis:
      time-to-live: 1m # default ttl
      key-prefix: '1.1.0:cache:' # default key prefix

#  main:
#    allow-circular-references: true

logging:
  level:
    "[com.ask]": debug
#    "[org.springframework.cache]": trace # CacheInterceptor 로그 확인 필요시 설정
