server:
  port: 9999

management:
  endpoint:
    health:
      show-details: always
    env:
      post:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: config-server
  profiles:
    active:
      native
#  cloud:
#    config:
#      server:
#        git:
#          uri: file:${user.home}/DEV/config-server-git
##          delete-untracked-branches: true
##          force-pull: true
#        encrypt:
#          enabled: false

encrypt:
  key-store:
    location: classpath:config-server.jks
    alias: config-server-key
    password: ask112
    secret: ask112
