server:
  port: 9001

logging:
  pattern:
    console: '%clr(%d{HH:mm:ss.SSS}){faint} %clr(%5p) %clr([%4line]){magenta} %clr(%-40.40logger{39}){cyan} %clr(:){red} %m%n%wEx'
  level:
    root: info
    com.ask: debug

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest