spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/batch
    username: root
    password: 111111

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
