spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/batch?profileSQL=true
    username: root
    password: 111111

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        jdbc:
          batch_size: 100
        #show_sql: true
        #format_sql: true
    open-in-view: false

  batch:
    job:
      names: ${job.name:NONE}
    jdbc:
      initialize-schema: never

logging:
  level:
    org.hibernate:
      SQL: debug