spring:
  application:
    name: api
  profiles:
    active: dev
  config:
    import: "optional:configserver:"

  cloud:
    config:
      uri: "http://localhost:8888"
      name: core,${spring.application.name}

encrypt:
  key-store:
    location: classpath:config-server.jks
    alias: config-server-key
    password: ask112
    secret: ask112
