#server:
#  servlet:
#    session:
#      cookie:
#        domain: test.com

spring:
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  messages:
    basename: message/message
    use-code-as-default-message: true

#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss # LocalDateTime 에는 적용 안됨

conditional:
  enabled: true
  name: ask

logging:
  level:
    "[org.springframework.web.filter]": debug
